"use client";

import * as Tabs from "@radix-ui/react-tabs";
import type { GradeLevel, SubmissionStatus, UserStatus } from "@prisma/client";
import Image from "next/image";
import Link from "next/link";
import { Ban, BookCheck, Check, Edit3, ExternalLink, FileText, Power, Quote, ShieldOff, Sparkles, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { banUser, deleteNoteAsAdmin, deleteSubject, moderateNote, moderateQuote, saveSubject, toggleRecommended, toggleSubject, unbanUser } from "@/actions/admin";
import { GRADE_LABELS, GRADE_OPTIONS, STATUS_LABELS } from "@/lib/constants";
import { formatDate } from "@/lib/utils";
import { Avatar } from "@/components/avatar";
import { Button, buttonStyles } from "@/components/ui/button";
import { ConfirmDialog, Dialog, DialogContent } from "@/components/ui/dialog";
import { HomeworkAdminPanel } from "@/components/homework-admin-panel";
import type { HomeworkDto, HomeworkWriterView } from "@/lib/homework-types";

type Asset = { id: string; contentType: string; originalName: string };
type AdminNote = { id: string; title: string; description: string | null; gradeLevel: GradeLevel; subjectName: string | null; customSubject: string | null; status: SubmissionStatus; rejectionReason: string | null; isRecommended: boolean; author: { id: string; name: string; picture: string | null }; assets: Asset[]; updatedAt: string };
type AdminQuote = { id: string; teacherName: string; quote: string; context: string | null; gradeLevel: GradeLevel | null; subjectName: string | null; status: SubmissionStatus; rejectionReason: string | null; author: { id: string; name: string; email: string }; updatedAt: string };
type AdminSubject = { id: string; name: string; gradeLevel: GradeLevel; sortOrder: number; isActive: boolean };
type AdminUser = { id: string; email: string; name: string; picture: string | null; status: UserStatus; banReason: string | null; createdAt: string; noteCount: number; quoteCount: number };
type AdminHomeworkWriter = HomeworkWriterView & { createdAt: string };

export function AdminDashboard({ status, notes, quotes, subjects, users, homeworkWriters, homework, counts }: { status: SubmissionStatus; notes: AdminNote[]; quotes: AdminQuote[]; subjects: AdminSubject[]; users: AdminUser[]; homeworkWriters: AdminHomeworkWriter[]; homework: HomeworkDto[]; counts: number[] }) {
  const [activeStatus, setActiveStatus] = useState(status);
  const visibleNotes = notes.filter((note) => note.status === activeStatus);
  const visibleQuotes = quotes.filter((quote) => quote.status === activeStatus);

  return (
    <Tabs.Root defaultValue="notes">
      <div className="grid gap-3 sm:grid-cols-3"><Stat label="Bekleyen not" value={counts[0]} icon={<BookCheck />} /><Stat label="Bekleyen söz" value={counts[1]} icon={<Quote />} /><Stat label="Yasaklı hesap" value={counts[2]} icon={<ShieldOff />} /></div>
      <Tabs.List className="mt-7 flex gap-1 overflow-x-auto rounded-2xl border border-line bg-card p-1.5"><Tab value="notes" label="Notlar" /><Tab value="quotes" label="Sözler" /><Tab value="subjects" label="Dersler" /><Tab value="users" label="Kullanıcılar" /><Tab value="homework" label="Ödevler" /></Tabs.List>
      <Tabs.Content value="notes" className="mt-6"><StatusFilters status={activeStatus} onChange={setActiveStatus} /><div className="mt-4 space-y-4">{visibleNotes.length ? visibleNotes.map((note) => <AdminNoteCard key={note.id} note={note} />) : <EmptyAdmin>Bu durumda not yok.</EmptyAdmin>}</div></Tabs.Content>
      <Tabs.Content value="quotes" className="mt-6"><StatusFilters status={activeStatus} onChange={setActiveStatus} /><div className="mt-4 space-y-4">{visibleQuotes.length ? visibleQuotes.map((quote) => <AdminQuoteCard key={quote.id} quote={quote} />) : <EmptyAdmin>Bu durumda öğretmen sözü yok.</EmptyAdmin>}</div></Tabs.Content>
      <Tabs.Content value="subjects" className="mt-6"><SubjectsPanel subjects={subjects} /></Tabs.Content>
      <Tabs.Content value="users" className="mt-6"><UsersPanel users={users} /></Tabs.Content>
      <Tabs.Content value="homework" className="mt-6"><HomeworkAdminPanel writers={homeworkWriters} homework={homework} /></Tabs.Content>
    </Tabs.Root>
  );
}

function Stat({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="paper-card flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-xl bg-bal-soft text-bal">{icon}</span><div><p className="text-2xl font-black">{value}</p><p className="text-xs font-bold text-muted">{label}</p></div></div>; }
function Tab({ value, label }: { value: string; label: string }) { return <Tabs.Trigger value={value} className="h-10 shrink-0 rounded-xl px-4 text-sm font-black text-muted data-[state=active]:bg-bal data-[state=active]:text-white">{label}</Tabs.Trigger>; }
function EmptyAdmin({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-dashed border-line p-8 text-center text-sm text-muted">{children}</div>; }
function StatusFilters({ status, onChange }: { status: SubmissionStatus; onChange: (status: SubmissionStatus) => void }) { return <div className="flex flex-wrap gap-2">{(["PENDING", "APPROVED", "REJECTED"] as SubmissionStatus[]).map((item) => <button key={item} type="button" aria-pressed={status === item} onClick={() => onChange(item)} className={buttonStyles({ variant: status === item ? "primary" : "outline", size: "sm" })}>{STATUS_LABELS[item]}</button>)}</div>; }

function AdminNoteCard({ note }: { note: AdminNote }) {
  const [rejectOpen, setRejectOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [banOpen, setBanOpen] = useState(false); const [reason, setReason] = useState(""); const [recommended, setRecommended] = useState(note.isRecommended); const [pending, startTransition] = useTransition(); const router = useRouter();
  function run(action: () => Promise<{ success: boolean; error?: string }>, message: string, close?: () => void) { startTransition(async () => { const result = await action(); if (!result.success) { toast.error(result.error); return; } toast.success(message); close?.(); router.refresh(); }); }
  return <article className="paper-card overflow-hidden"><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_18rem]"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-bal px-2.5 py-1 text-[10px] font-black uppercase text-white">{GRADE_LABELS[note.gradeLevel]}</span><span className="rounded-full bg-bal-soft px-2.5 py-1 text-[10px] font-black uppercase text-bal">{note.subjectName || note.customSubject || "Diğer"}</span>{note.isRecommended ? <span className="rounded-full bg-ink px-2.5 py-1 text-[10px] font-black uppercase text-white">Önerilen</span> : null}</div><h3 className="mt-3 text-xl font-black">{note.title}</h3>{note.description ? <p className="mt-2 text-sm leading-6 text-muted">{note.description}</p> : null}<div className="mt-4 flex items-center gap-2 text-xs text-muted"><Avatar name={note.author.name} picture={note.author.picture} className="size-7" /><span className="font-bold text-ink">{note.author.name}</span><span>· {formatDate(note.updatedAt)}</span></div>{note.rejectionReason ? <p className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-800">Son ret nedeni: {note.rejectionReason}</p> : null}</div><div className="grid grid-cols-2 gap-2">{note.assets.slice(0, 4).map((asset) => asset.contentType.startsWith("image/") ? <a key={asset.id} href={`/api/assets/${asset.id}`} target="_blank" rel="noreferrer" className="relative aspect-square overflow-hidden rounded-xl border border-line"><Image src={`/api/assets/${asset.id}`} alt={asset.originalName} fill unoptimized className="object-cover" /></a> : <a key={asset.id} href={`/api/assets/${asset.id}`} target="_blank" rel="noreferrer" className="flex aspect-square flex-col items-center justify-center rounded-xl border border-line bg-paper-deep p-2 text-center text-xs font-bold text-bal"><FileText /><span className="mt-2 line-clamp-2">{asset.originalName}</span></a>)}</div></div>
    <div className="flex flex-wrap gap-2 border-t border-line bg-paper-deep/45 px-5 py-4"><Link href={`/notlar/${note.id}`} target="_blank" className={buttonStyles({ variant: "outline", size: "sm" })}><ExternalLink size={15} /> Aç</Link>{note.status !== "APPROVED" ? <><label className="inline-flex h-10 items-center gap-2 rounded-xl border border-line bg-card px-3 text-sm font-bold"><input type="checkbox" checked={recommended} onChange={(event) => setRecommended(event.target.checked)} /> Önerilen</label><Button size="sm" disabled={pending} onClick={() => run(() => moderateNote({ id: note.id, decision: "APPROVED", recommended }), "Not onaylandı.")}><Check size={15} /> Onayla</Button></> : <Button variant={note.isRecommended ? "secondary" : "outline"} size="sm" onClick={() => run(() => toggleRecommended(note.id), note.isRecommended ? "Önerilerden çıkarıldı." : "Önerilere eklendi.")}><Sparkles size={15} /> {note.isRecommended ? "Öneriden Çıkar" : "Öner"}</Button>}<Button variant="outline" size="sm" onClick={() => { setReason(note.rejectionReason || ""); setRejectOpen(true); }}><X size={15} /> Reddet</Button><Button variant="ghost" size="sm" onClick={() => setDeleteOpen(true)}><Trash2 size={15} /> Sil</Button><Button variant="danger" size="sm" onClick={() => { setReason(""); setBanOpen(true); }}><Ban size={15} /> Sil ve Yasakla</Button></div>
    <ConfirmDialog open={rejectOpen} onOpenChange={setRejectOpen} title="Notu keşfetten çıkar" description="Not doğrudan bağlantıyla erişilebilir kalır; yazar nedeni profilinde görür." confirmLabel="Reddet" danger={false} pending={pending} onConfirm={() => run(() => moderateNote({ id: note.id, decision: "REJECTED", reason }), "Not reddedildi.", () => setRejectOpen(false))}><label className="label">Yazara gösterilecek neden</label><textarea className="field" value={reason} onChange={(e) => setReason(e.target.value)} required /></ConfirmDialog>
    <ConfirmDialog open={deleteOpen} onOpenChange={setDeleteOpen} title="Notu kalıcı olarak sil" description="Doğrudan bağlantı 404 dönecek ve tüm dosyalar kaldırılacak." confirmLabel="Kalıcı Olarak Sil" pending={pending} onConfirm={() => run(() => deleteNoteAsAdmin(note.id), "Not kalıcı olarak silindi.", () => setDeleteOpen(false))} />
    <ConfirmDialog open={banOpen} onOpenChange={setBanOpen} title="Notu sil ve kullanıcıyı yasakla" description="Kullanıcının tüm notları, sözleri, oyları ve oturumları silinecek. BAL ID hesabı etkilenmez." confirmLabel="Sil ve Yasakla" pending={pending} onConfirm={() => run(() => banUser({ userId: note.author.id, noteId: note.id, reason }), "Kullanıcı yasaklandı ve içerikleri kaldırıldı.", () => setBanOpen(false))}><label className="label">Yasaklama nedeni</label><textarea className="field" value={reason} onChange={(e) => setReason(e.target.value)} required /></ConfirmDialog>
  </article>;
}

function AdminQuoteCard({ quote }: { quote: AdminQuote }) {
  const [open, setOpen] = useState(false); const [reason, setReason] = useState(""); const [pending, startTransition] = useTransition(); const router = useRouter();
  function decide(decision: "APPROVED" | "REJECTED") { startTransition(async () => { const result = await moderateQuote({ id: quote.id, decision, reason }); if (!result.success) { toast.error(result.error); return; } toast.success(decision === "APPROVED" ? "Söz onaylandı." : "Söz reddedildi."); setOpen(false); router.refresh(); }); }
  return <article className="paper-card p-5"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><blockquote className="text-xl font-black">“{quote.quote}”</blockquote><p className="mt-2 text-sm font-bold text-bal">— {quote.teacherName}</p>{quote.context ? <p className="mt-1 text-xs text-muted">{quote.context}</p> : null}<p className="mt-3 text-xs font-bold text-muted">{quote.subjectName || "Ders belirtilmedi"}{quote.gradeLevel ? ` · ${GRADE_LABELS[quote.gradeLevel]}` : ""}</p><p className="mt-2 text-xs text-muted">Gönderen: {quote.author.name} · {formatDate(quote.updatedAt)}</p></div><div className="flex shrink-0 flex-wrap gap-2">{quote.status !== "APPROVED" ? <Button size="sm" onClick={() => decide("APPROVED")} disabled={pending}><Check size={15} /> Onayla</Button> : null}<Button variant="outline" size="sm" onClick={() => setOpen(true)}><X size={15} /> Reddet</Button></div></div><ConfirmDialog open={open} onOpenChange={setOpen} title="Sözü reddet" description="Söz keşfette görünmeyecek; gönderene bu neden gösterilecek." confirmLabel="Reddet" pending={pending} onConfirm={() => decide("REJECTED")}><label className="label">Ret nedeni</label><textarea className="field" value={reason} onChange={(e) => setReason(e.target.value)} /></ConfirmDialog></article>;
}

function SubjectsPanel({ subjects }: { subjects: AdminSubject[] }) {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AdminSubject | null>(null); const [deleteId, setDeleteId] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const router = useRouter();
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(async () => { const result = await saveSubject({ id: editing?.id, name: String(data.get("name") || ""), gradeLevel: String(data.get("gradeLevel")), sortOrder: Number(data.get("sortOrder")) }); if (!result.success) { toast.error(result.error); return; } toast.success("Ders kaydedildi."); setOpen(false); setEditing(null); router.refresh(); }); }
  return <><div className="mb-4 flex justify-end"><Button onClick={() => { setEditing(null); setOpen(true); }}>Yeni Ders</Button></div><div className="overflow-x-auto rounded-2xl border border-line bg-card"><table className="w-full min-w-[34rem] text-left text-sm"><thead className="bg-paper-deep text-xs uppercase text-muted"><tr><th className="p-3">Sınıf</th><th className="p-3">Ders</th><th className="hidden p-3 sm:table-cell">Sıra</th><th className="p-3 text-right">İşlemler</th></tr></thead><tbody>{subjects.map((subject) => <tr key={subject.id} className="border-t border-line"><td className="p-3 font-bold">{GRADE_LABELS[subject.gradeLevel]}</td><td className={`p-3 ${subject.isActive ? "font-bold" : "text-muted line-through"}`}>{subject.name}</td><td className="hidden p-3 text-muted sm:table-cell">{subject.sortOrder}</td><td className="p-3"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" aria-label="Dersi düzenle" onClick={() => { setEditing(subject); setOpen(true); }}><Edit3 size={15} /></Button><Button variant="ghost" size="icon" aria-label={subject.isActive ? "Pasifleştir" : "Etkinleştir"} onClick={() => startTransition(async () => { const result = await toggleSubject(subject.id); if (!result.success) toast.error(result.error); router.refresh(); })}><Power size={15} /></Button><Button variant="ghost" size="icon" aria-label="Dersi sil" onClick={() => setDeleteId(subject.id)}><Trash2 size={15} /></Button></div></td></tr>)}</tbody></table></div><Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing ? "Dersi düzenle" : "Yeni ders ekle"}><form onSubmit={submit} className="space-y-4"><div><label className="label">Ders adı</label><input className="field" name="name" defaultValue={editing?.name} required minLength={2} maxLength={60} /></div><div><label className="label">Sınıf</label><select className="field" name="gradeLevel" defaultValue={editing?.gradeLevel || "PREP"}>{GRADE_OPTIONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><div><label className="label">Sıra</label><input className="field" name="sortOrder" type="number" min={0} max={999} defaultValue={editing?.sortOrder || 0} /></div><Button type="submit" disabled={pending} className="w-full">Kaydet</Button></form></DialogContent></Dialog><ConfirmDialog open={Boolean(deleteId)} onOpenChange={(value) => !value && setDeleteId(null)} title="Dersi sil" description="Kullanılan dersler silinemez; gerekirse pasifleştirin." confirmLabel="Dersi Sil" pending={pending} onConfirm={() => startTransition(async () => { if (!deleteId) return; const result = await deleteSubject(deleteId); if (!result.success) { toast.error(result.error); return; } setDeleteId(null); router.refresh(); })} /></>;
}

function UsersPanel({ users }: { users: AdminUser[] }) {
  const [target, setTarget] = useState<AdminUser | null>(null); const [reason, setReason] = useState(""); const [pending, startTransition] = useTransition(); const router = useRouter();
  return <><div className="space-y-3">{users.map((user) => <article key={user.id} className="paper-card flex flex-col justify-between gap-4 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><Avatar name={user.name} picture={user.picture} /><div><p className="font-black">{user.name}</p><p className="text-xs text-muted">{user.email}</p><p className="mt-1 text-[10px] font-bold uppercase text-muted">{user.noteCount} not · {user.quoteCount} söz · {user.status === "BANNED" ? "Yasaklı" : "Aktif"}</p>{user.banReason ? <p className="mt-1 text-xs text-red-700">{user.banReason}</p> : null}</div></div>{user.status === "BANNED" ? <Button variant="outline" size="sm" onClick={() => startTransition(async () => { const result = await unbanUser(user.id); if (!result.success) { toast.error(result.error); return; } toast.success("Yasak kaldırıldı; silinen içerikler geri gelmez."); router.refresh(); })}>Yasağı Kaldır</Button> : <Button variant="danger" size="sm" onClick={() => { setTarget(user); setReason(""); }}><Ban size={15} /> Yasakla</Button>}</article>)}</div><ConfirmDialog open={Boolean(target)} onOpenChange={(value) => !value && setTarget(null)} title="Kullanıcıyı yasakla" description="Tüm içerikleri, oyları ve oturumları kaldırılacak. BAL ID hesabına dokunulmaz." confirmLabel="Kullanıcıyı Yasakla" pending={pending} onConfirm={() => startTransition(async () => { if (!target) return; const result = await banUser({ userId: target.id, reason }); if (!result.success) { toast.error(result.error); return; } toast.success("Kullanıcı yasaklandı."); setTarget(null); router.refresh(); })}><label className="label">Yasaklama nedeni</label><textarea className="field" value={reason} onChange={(e) => setReason(e.target.value)} /></ConfirmDialog></>;
}
